_BASE_: "Base-Pretrain.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE: 
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
#    NORM: "SyncBN"
    NORM: "GN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
  FCOS:
#    INFERENCE_TH_TRAIN: 0.7
#    INFERENCE_TH_TEST: 0.45
    INFERENCE_TH_TEST: [0.1, 0.2, 0.3, 0.4, 0.5]
    INFERENCE_TH_TRAIN: [0.1, 0.2, 0.3, 0.4, 0.5]
    INFERENCE_TH_TEST_EVAL_FORMAT: 0.5
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  STEPS: (40000, 220000)
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "output/batext/pretrain/different_pre_nms_v2_attn_R_50"

