_BASE_: "Base-Pretrain.yaml"
MODEL:
  MASK_ON: True
  TEXTFUSENET_MUTIL_PATH_FUSE_ON: True
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE: 
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
#    NORM: "SyncBN"
    NORM: "GN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    POOLER_RESOLUTION: (8,128)
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
  ROI_HEADS:
    NAME: "Seg_Text_Head"
    IOU_THRESHOLDS: [ 0.5 ]
SOLVER:
#  IMS_PER_BATCH: 8
#  IMS_PER_BATCH: 3
  IMS_PER_BATCH: 2
  BASE_LR: 0.01
#  BASE_LR: 0.01
  STEPS: (160000, 220000)
#  MAX_ITER: 260000
#  MAX_ITER: 350000
  MAX_ITER: 520000
#  CHECKPOINT_PERIOD: 20000
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 20000
OUTPUT_DIR: "output/batext/pretrain/global_context_v2_attn_R_50"

