_BASE_: "Base-Pretrain.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE: 
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
#    NORM: "SyncBN"
    NORM: "GN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
  PREDICT_PROB:
    CHANNELS: 256
    NUM_FPN_FEATURES: 5
    NUM_CONV3: 4
    FPN_FEATURES_FUSED_LEVEL: 2
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001  #0.01
  STEPS: (40000, )
  MAX_ITER: 80000  #260000
  CHECKPOINT_PERIOD: 20000
DATASETS:
  TRAIN: ("ctw1500_word_train",)
  TEST: ("ctw1500_word_test",)
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "output/batext/pretrain/pred_prob/v2_attn_R_50"