_BASE_: "Base-TotalText.yaml"
MODEL:
  MASK_ON: True
  TEXTFUSENET_MUTIL_PATH_FUSE_ON: True
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
    NORM: "GN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    POOLER_RESOLUTION: (8,128)
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
  FCOS:
    # Best e2e: 0.5; Best det: 0.4
    INFERENCE_TH_TEST: 0.5
  ROI_HEADS:
    NAME: "Seg_Text_Head"
    IOU_THRESHOLDS: [ 0.5 ]
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
#  MAX_ITER: 5000
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output/batext/total_text/add_global_v2_attn_R_50"
