_BASE_: "../Base-CTW1500.yaml"
MODEL:
  MASK_ON: True
  TEXTFUSENET_MUTIL_PATH_FUSE_ON: True
  WEIGHTS: "model_v2_pretrain.pth"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
    NORM: "GN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
  FCOS:
    # Best e2e: 0.5; Best det: 0.3
    INFERENCE_TH_TEST: 0.5
  ROI_HEADS:
    NAME: "Seg_Text_Head"
    IOU_THRESHOLDS: [ 0.5 ]
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (80000, )
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
DATASETS:
  TRAIN: ("ctw1500_word_train",)
  TEST: ("ctw1500_word_test",)
OUTPUT_DIR: "output/batext/ctw1500/add_global_v2_attn_R_50"
