_BASE_: "../Base-CTW1500.yaml"
MODEL:
  WEIGHTS: "model_v2_pretrain.pth"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
    NORM: "SyncBN"
#    NORM: "GN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
  FCOS:
    NMS_TH: 0.1
    # Best e2e: 0.5; Best det: 0.3
    INFERENCE_TH_TEST: 0.0
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  STEPS: (320000, )
  MAX_ITER: 400000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "output/batext/ctw1500/poly_nms/pre_nms_0.05+2bh_32w+poly_nms_v2_attn_R_50"