_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  IMS_PER_BATCH: 9
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (106000, 142000)
  MAX_ITER: 160000
OUTPUT_DIR: "output/fcos/attention+weigthed+R_50_1x"
