_BASE_: "Base-Pretrain.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE: 
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
#    NORM: "SyncBN"
    NORM: "GN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001  #0.01
  STEPS: ()
  MAX_ITER: 80000  #260000
  CHECKPOINT_PERIOD: 20000
TEST:
  EVAL_PERIOD: 20000
OUTPUT_DIR: "output/batext/pretrain/Resize_FPN_nearest/v2_attn_R_50"